-- Initial schema for empty production databases.
-- Generated from Hibernate schema export against PostgreSQL; existing non-empty DBs are baselined by Flyway.
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_action_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_action_logs (
    admin_action_log_id bigint NOT NULL,
    admin_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    target_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    target_type character varying(20) NOT NULL,
    action character varying(40) NOT NULL,
    ip_address character varying(100),
    reason character varying(500) NOT NULL,
    user_agent character varying(500),
    CONSTRAINT admin_action_logs_action_check CHECK (((action)::text = ANY ((ARRAY['HIDE_POST'::character varying, 'RESTORE_POST'::character varying, 'DELETE_POST'::character varying, 'LOCK_POST'::character varying, 'UNLOCK_POST'::character varying, 'HIDE_COMMENT'::character varying, 'RESTORE_COMMENT'::character varying, 'DELETE_COMMENT'::character varying, 'SANCTION_USER'::character varying, 'HANDLE_REPORT'::character varying, 'UPDATE_USER_ROLE'::character varying])::text[]))),
    CONSTRAINT admin_action_logs_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['POST'::character varying, 'COMMENT'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: admin_action_logs_admin_action_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_action_logs ALTER COLUMN admin_action_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_action_logs_admin_action_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    display_order integer NOT NULL,
    is_representative boolean NOT NULL,
    attachment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    file_size bigint NOT NULL,
    target_id bigint,
    updated_at timestamp(6) without time zone,
    uploader_id bigint NOT NULL,
    extension character varying(20),
    file_category character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    target_type character varying(30),
    content_type character varying(100) NOT NULL,
    checksum character varying(128),
    storage_path character varying(500) NOT NULL,
    original_name character varying(255) NOT NULL,
    stored_name character varying(255) NOT NULL,
    CONSTRAINT attachments_file_category_check CHECK (((file_category)::text = ANY ((ARRAY['IMAGE'::character varying, 'ATTACHMENT'::character varying, 'THUMBNAIL'::character varying, 'PROFILE'::character varying])::text[]))),
    CONSTRAINT attachments_status_check CHECK (((status)::text = ANY ((ARRAY['TEMP'::character varying, 'ACTIVE'::character varying, 'DELETED'::character varying, 'ORPHANED'::character varying])::text[]))),
    CONSTRAINT attachments_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['POST'::character varying, 'COMMENT'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: attachments_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN attachment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.boards (
    is_active boolean NOT NULL,
    board_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    CONSTRAINT boards_type_check CHECK (((type)::text = ANY ((ARRAY['NORMAL'::character varying, 'RECRUIT'::character varying])::text[])))
);


--
-- Name: boards_board_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.boards ALTER COLUMN board_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boards_board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_histories (
    actor_id bigint NOT NULL,
    comment_history_id bigint NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    action character varying(40) NOT NULL,
    reason character varying(500),
    content text,
    CONSTRAINT comment_histories_action_check CHECK (((action)::text = ANY ((ARRAY['CREATED'::character varying, 'UPDATED'::character varying, 'USER_DELETED'::character varying, 'ADMIN_HIDDEN'::character varying, 'ADMIN_RESTORED'::character varying, 'ADMIN_DELETED'::character varying, 'AUTO_HIDDEN'::character varying])::text[]))),
    CONSTRAINT comment_histories_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'DELETED'::character varying, 'ADMIN_DELETED'::character varying, 'BLOCKED'::character varying])::text[])))
);


--
-- Name: comment_histories_comment_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment_histories ALTER COLUMN comment_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_histories_comment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_likes (
    comment_id bigint NOT NULL,
    comment_like_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: comment_likes_comment_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment_likes ALTER COLUMN comment_like_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_likes_comment_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    parent_comment_id bigint,
    post_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    status character varying(30),
    delete_reason character varying(500),
    content text NOT NULL,
    CONSTRAINT comments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'DELETED'::character varying, 'ADMIN_DELETED'::character varying, 'BLOCKED'::character varying])::text[])))
);


--
-- Name: comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: info_articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.info_articles (
    source_date date NOT NULL,
    bookmark_count bigint NOT NULL,
    created_at timestamp(6) without time zone,
    info_article_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    view_count bigint NOT NULL,
    category character varying(20) NOT NULL,
    tag character varying(30) NOT NULL,
    source_name character varying(50) NOT NULL,
    meta character varying(100) NOT NULL,
    title character varying(150) NOT NULL,
    image_url character varying(500) NOT NULL,
    content text NOT NULL,
    CONSTRAINT info_articles_category_check CHECK (((category)::text = ANY ((ARRAY['NEWS'::character varying, 'CONTEST'::character varying, 'LAB'::character varying, 'RESOURCE'::character varying])::text[])))
);


--
-- Name: info_articles_info_article_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.info_articles ALTER COLUMN info_article_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.info_articles_info_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: instance_application_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instance_application_files (
    uploaded_at character varying(20) NOT NULL,
    application_id character varying(30) NOT NULL,
    file_size character varying(50) NOT NULL,
    file_name character varying(255) NOT NULL
);


--
-- Name: instance_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.instance_applications (
    approved_at date,
    requested_at date NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    duration character varying(20) NOT NULL,
    instance_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    student_id character varying(20) NOT NULL,
    application_id character varying(30) NOT NULL,
    spec_cpu character varying(30) NOT NULL,
    spec_disk character varying(30) NOT NULL,
    spec_ram character varying(30) NOT NULL,
    applicant_name character varying(50) NOT NULL,
    key_email character varying(120) NOT NULL,
    admin_note text,
    purpose text NOT NULL
);


--
-- Name: member_service_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_service_features (
    service_id character varying(80) NOT NULL,
    feature character varying(255) NOT NULL
);


--
-- Name: member_service_stack; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_service_stack (
    service_id character varying(80) NOT NULL,
    stack_name character varying(80) NOT NULL
);


--
-- Name: member_service_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_service_tags (
    tag character varying(50) NOT NULL,
    service_id character varying(80) NOT NULL
);


--
-- Name: member_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_services (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    visibility character varying(30) NOT NULL,
    category character varying(50) NOT NULL,
    owner_name character varying(50) NOT NULL,
    service_id character varying(80) NOT NULL,
    audience character varying(100) NOT NULL,
    period character varying(100) NOT NULL,
    title character varying(100) NOT NULL,
    github_url character varying(500) NOT NULL,
    image_url character varying(500) NOT NULL,
    service_url character varying(500) NOT NULL,
    description text NOT NULL,
    summary character varying(255) NOT NULL
);


--
-- Name: post_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_histories (
    actor_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    post_history_id bigint NOT NULL,
    post_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(30) NOT NULL,
    action character varying(40) NOT NULL,
    title character varying(100) NOT NULL,
    reason character varying(500),
    content text,
    CONSTRAINT post_histories_action_check CHECK (((action)::text = ANY ((ARRAY['CREATED'::character varying, 'UPDATED'::character varying, 'USER_DELETED'::character varying, 'ADMIN_HIDDEN'::character varying, 'ADMIN_RESTORED'::character varying, 'ADMIN_DELETED'::character varying, 'AUTO_HIDDEN'::character varying])::text[]))),
    CONSTRAINT post_histories_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'DELETED'::character varying, 'ADMIN_DELETED'::character varying, 'BLOCKED'::character varying, 'PENDING'::character varying])::text[])))
);


--
-- Name: post_histories_post_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_histories ALTER COLUMN post_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_histories_post_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_likes (
    created_at timestamp(6) without time zone,
    post_id bigint NOT NULL,
    post_like_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: post_likes_post_like_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_likes ALTER COLUMN post_like_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_likes_post_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.posts (
    is_locked boolean,
    is_notice boolean,
    view_count integer NOT NULL,
    board_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    deleted_by bigint,
    post_id bigint NOT NULL,
    thumbnail_attachment_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    status character varying(30),
    title character varying(100) NOT NULL,
    delete_reason character varying(500),
    content text,
    CONSTRAINT posts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'DELETED'::character varying, 'ADMIN_DELETED'::character varying, 'BLOCKED'::character varying, 'PENDING'::character varying])::text[])))
);


--
-- Name: posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.posts ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_user_activity_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_user_activity_logs (
    sort_order integer NOT NULL,
    activity_log_id bigint NOT NULL,
    profile_id bigint NOT NULL,
    type character varying(30) NOT NULL,
    public_id character varying(50) NOT NULL,
    time_label character varying(50) NOT NULL,
    repository character varying(100) NOT NULL,
    title character varying(150) NOT NULL,
    description character varying(500) NOT NULL
);


--
-- Name: public_user_activity_logs_activity_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_user_activity_logs ALTER COLUMN activity_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_user_activity_logs_activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_user_awards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_user_awards (
    awarded_at date NOT NULL,
    sort_order integer NOT NULL,
    award_id bigint NOT NULL,
    profile_id bigint NOT NULL,
    category character varying(30) NOT NULL,
    public_id character varying(50) NOT NULL,
    rank_label character varying(50) NOT NULL,
    organizer character varying(150) NOT NULL,
    title character varying(150) NOT NULL,
    credential_url character varying(500),
    description character varying(500) NOT NULL
);


--
-- Name: public_user_awards_award_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_user_awards ALTER COLUMN award_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_user_awards_award_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_user_profile_repositories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_user_profile_repositories (
    profile_id bigint NOT NULL,
    repository_name character varying(100) NOT NULL
);


--
-- Name: public_user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.public_user_profiles (
    github_commits integer NOT NULL,
    is_me boolean NOT NULL,
    solved_count integer NOT NULL,
    total_points integer NOT NULL,
    created_at timestamp(6) without time zone,
    profile_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    initials character varying(10) NOT NULL,
    grade_label character varying(20) NOT NULL,
    solved_tier character varying(20) NOT NULL,
    tone character varying(20) NOT NULL,
    github_handle character varying(39) NOT NULL,
    name character varying(50) NOT NULL,
    recent_commit character varying(50) NOT NULL,
    role character varying(50) NOT NULL,
    solved_handle character varying(50) NOT NULL,
    lab character varying(100) NOT NULL,
    focus character varying(255) NOT NULL,
    github_url character varying(255) NOT NULL
);


--
-- Name: public_user_profiles_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.public_user_profiles ALTER COLUMN profile_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_user_profiles_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruit_applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_applications (
    application_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    submitted_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    status character varying(30) NOT NULL,
    recruit_id character varying(80) NOT NULL,
    role character varying(100) NOT NULL,
    body text NOT NULL
);


--
-- Name: recruit_applications_application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruit_applications ALTER COLUMN application_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruit_applications_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruit_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_comments (
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    author_initials character varying(10) NOT NULL,
    author_tone character varying(20) NOT NULL,
    author character varying(50) NOT NULL,
    recruit_id character varying(80) NOT NULL,
    content text NOT NULL
);


--
-- Name: recruit_comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruit_comments ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruit_comments_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruit_detail_paragraphs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_detail_paragraphs (
    recruit_id character varying(80) NOT NULL,
    paragraph text NOT NULL
);


--
-- Name: recruit_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_posts (
    current_members integer NOT NULL,
    max_members integer NOT NULL,
    trust_score double precision NOT NULL,
    bookmarks bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    views bigint NOT NULL,
    host_initials character varying(10) NOT NULL,
    host_tone character varying(20) NOT NULL,
    category character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    host character varying(50) NOT NULL,
    expected_duration character varying(80) NOT NULL,
    recruit_id character varying(80) NOT NULL,
    host_role character varying(100) NOT NULL,
    meeting_type character varying(150) NOT NULL,
    title character varying(150) NOT NULL,
    short_desc character varying(300) NOT NULL
);


--
-- Name: recruit_process_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_process_items (
    recruit_id character varying(80) NOT NULL,
    process_item character varying(255) NOT NULL
);


--
-- Name: recruit_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_roles (
    current_count integer NOT NULL,
    max_count integer NOT NULL,
    sort_order integer NOT NULL,
    role_id bigint NOT NULL,
    label character varying(80) NOT NULL,
    recruit_id character varying(80) NOT NULL
);


--
-- Name: recruit_roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruit_roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruit_roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruit_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_tags (
    tag character varying(50) NOT NULL,
    recruit_id character varying(80) NOT NULL
);


--
-- Name: recruit_tech_stack; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruit_tech_stack (
    recruit_id character varying(80) NOT NULL,
    tech_name character varying(80) NOT NULL
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
    created_at timestamp(6) without time zone,
    handled_at timestamp(6) without time zone,
    handled_by bigint,
    report_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    target_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    target_type character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    reason_type character varying(40) NOT NULL,
    reason_detail character varying(1000),
    CONSTRAINT reports_reason_type_check CHECK (((reason_type)::text = ANY ((ARRAY['ABUSE'::character varying, 'SEXUAL_CONTENT'::character varying, 'SPAM'::character varying, 'PERSONAL_INFO'::character varying, 'FALSE_INFORMATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'AUTO_HIDDEN'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT reports_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['POST'::character varying, 'COMMENT'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources (
    created_at timestamp(6) without time zone,
    file_size bigint NOT NULL,
    post_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    file_type character varying(50) NOT NULL,
    file_url character varying(500) NOT NULL,
    file_name character varying(255) NOT NULL
);


--
-- Name: resources_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resources ALTER COLUMN resource_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_inquiries (
    created_date date NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    inquiry_id character varying(30) NOT NULL,
    status character varying(30) NOT NULL,
    status_class character varying(40) NOT NULL,
    author_name character varying(50) NOT NULL,
    title character varying(120) NOT NULL,
    content text NOT NULL,
    summary character varying(255) NOT NULL
);


--
-- Name: site_contents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_contents (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content_key character varying(50) NOT NULL,
    title character varying(150) NOT NULL,
    chips character varying(500) NOT NULL,
    description text NOT NULL
);


--
-- Name: user_sanctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_sanctions (
    created_at timestamp(6) without time zone,
    created_by bigint NOT NULL,
    end_at timestamp(6) without time zone,
    start_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    user_sanction_id bigint NOT NULL,
    type character varying(40) NOT NULL,
    reason character varying(500) NOT NULL,
    CONSTRAINT user_sanctions_type_check CHECK (((type)::text = ANY ((ARRAY['WARNING'::character varying, 'POST_RESTRICTED'::character varying, 'COMMENT_RESTRICTED'::character varying, 'TEMP_SUSPENDED'::character varying, 'ACCOUNT_SUSPENDED'::character varying, 'PERMANENT_BANNED'::character varying])::text[])))
);


--
-- Name: user_sanctions_user_sanction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_sanctions ALTER COLUMN user_sanction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sanctions_user_sanction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    birth_date date,
    grade integer,
    verified boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    academic_status character varying(20) NOT NULL,
    gender character varying(20),
    student_id character varying(20) NOT NULL,
    role character varying(30),
    github_id character varying(39) NOT NULL,
    baekjoon_id character varying(50),
    name character varying(50) NOT NULL,
    nickname character varying(50),
    department character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    lab character varying(150),
    profile_bio character varying(1000),
    profile_shared_repositories character varying(1000),
    linkedin_url character varying(255),
    profile_activity_note text,
    profile_award_note text,
    CONSTRAINT users_academic_status_check CHECK (((academic_status)::text = ANY ((ARRAY['PROFESSOR'::character varying, 'ASSISTANT'::character varying, 'ENROLLED'::character varying, 'ON_LEAVE'::character varying, 'GRADUATED'::character varying, 'GENERAL'::character varying])::text[]))),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying, 'PREFER_NOT_TO_SAY'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'STAFF'::character varying, 'SUPER_ADMIN'::character varying])::text[])))
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_action_logs admin_action_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_action_logs
    ADD CONSTRAINT admin_action_logs_pkey PRIMARY KEY (admin_action_log_id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (attachment_id);


--
-- Name: boards boards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (board_id);


--
-- Name: comment_histories comment_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_histories
    ADD CONSTRAINT comment_histories_pkey PRIMARY KEY (comment_history_id);


--
-- Name: comment_likes comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (comment_like_id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (comment_id);


--
-- Name: info_articles info_articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.info_articles
    ADD CONSTRAINT info_articles_pkey PRIMARY KEY (info_article_id);


--
-- Name: instance_applications instance_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_applications
    ADD CONSTRAINT instance_applications_pkey PRIMARY KEY (application_id);


--
-- Name: member_services member_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_services
    ADD CONSTRAINT member_services_pkey PRIMARY KEY (service_id);


--
-- Name: post_histories post_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_histories
    ADD CONSTRAINT post_histories_pkey PRIMARY KEY (post_history_id);


--
-- Name: post_likes post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_pkey PRIMARY KEY (post_like_id);


--
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (post_id);


--
-- Name: public_user_activity_logs public_user_activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_activity_logs
    ADD CONSTRAINT public_user_activity_logs_pkey PRIMARY KEY (activity_log_id);


--
-- Name: public_user_awards public_user_awards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_awards
    ADD CONSTRAINT public_user_awards_pkey PRIMARY KEY (award_id);


--
-- Name: public_user_profiles public_user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_profiles
    ADD CONSTRAINT public_user_profiles_pkey PRIMARY KEY (profile_id);


--
-- Name: recruit_applications recruit_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_applications
    ADD CONSTRAINT recruit_applications_pkey PRIMARY KEY (application_id);


--
-- Name: recruit_comments recruit_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_comments
    ADD CONSTRAINT recruit_comments_pkey PRIMARY KEY (comment_id);


--
-- Name: recruit_posts recruit_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_posts
    ADD CONSTRAINT recruit_posts_pkey PRIMARY KEY (recruit_id);


--
-- Name: recruit_roles recruit_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_roles
    ADD CONSTRAINT recruit_roles_pkey PRIMARY KEY (role_id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (report_id);


--
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (resource_id);


--
-- Name: service_inquiries service_inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_inquiries
    ADD CONSTRAINT service_inquiries_pkey PRIMARY KEY (inquiry_id);


--
-- Name: site_contents site_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_contents
    ADD CONSTRAINT site_contents_pkey PRIMARY KEY (content_key);


--
-- Name: boards uk_boards_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT uk_boards_name UNIQUE (name);


--
-- Name: comment_likes uk_comment_like_user_comment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT uk_comment_like_user_comment UNIQUE (user_id, comment_id);


--
-- Name: post_likes uk_post_like_user_post; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT uk_post_like_user_post UNIQUE (user_id, post_id);


--
-- Name: public_user_profiles uk_public_user_profiles_github; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_profiles
    ADD CONSTRAINT uk_public_user_profiles_github UNIQUE (github_handle);


--
-- Name: reports uk_reports_reporter_target; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT uk_reports_reporter_target UNIQUE (reporter_id, target_type, target_id);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users uk_users_github_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_github_id UNIQUE (github_id);


--
-- Name: users uk_users_linkedin_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_linkedin_url UNIQUE (linkedin_url);


--
-- Name: users uk_users_nickname; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_nickname UNIQUE (nickname);


--
-- Name: users uk_users_student_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_student_id UNIQUE (student_id);


--
-- Name: user_sanctions user_sanctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sanctions
    ADD CONSTRAINT user_sanctions_pkey PRIMARY KEY (user_sanction_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_info_articles_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_info_articles_category ON public.info_articles USING btree (category);


--
-- Name: idx_info_articles_source_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_info_articles_source_date ON public.info_articles USING btree (source_date);


--
-- Name: idx_instance_applications_requested_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instance_applications_requested_at ON public.instance_applications USING btree (requested_at);


--
-- Name: idx_instance_applications_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instance_applications_status ON public.instance_applications USING btree (status);


--
-- Name: idx_member_services_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_services_category ON public.member_services USING btree (category);


--
-- Name: idx_member_services_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_services_status ON public.member_services USING btree (status);


--
-- Name: idx_public_user_profiles_grade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_public_user_profiles_grade ON public.public_user_profiles USING btree (grade_label);


--
-- Name: idx_public_user_profiles_lab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_public_user_profiles_lab ON public.public_user_profiles USING btree (lab);


--
-- Name: idx_recruit_applications_recruit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recruit_applications_recruit ON public.recruit_applications USING btree (recruit_id);


--
-- Name: idx_recruit_applications_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recruit_applications_user ON public.recruit_applications USING btree (user_id);


--
-- Name: idx_recruit_comments_recruit; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recruit_comments_recruit ON public.recruit_comments USING btree (recruit_id);


--
-- Name: idx_recruit_posts_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recruit_posts_category ON public.recruit_posts USING btree (category);


--
-- Name: idx_recruit_posts_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recruit_posts_status ON public.recruit_posts USING btree (status);


--
-- Name: idx_reports_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reports_target ON public.reports USING btree (target_type, target_id);


--
-- Name: idx_service_inquiries_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_service_inquiries_status ON public.service_inquiries USING btree (status);


--
-- Name: idx_user_sanctions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_sanctions_user ON public.user_sanctions USING btree (user_id);


--
-- Name: idx_users_academic_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_academic_status ON public.users USING btree (academic_status);


--
-- Name: idx_users_grade; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_grade ON public.users USING btree (grade);


--
-- Name: idx_users_lab; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_lab ON public.users USING btree (lab);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: recruit_detail_paragraphs fk13kuwiiqbg30iwla53ikqlhqk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_detail_paragraphs
    ADD CONSTRAINT fk13kuwiiqbg30iwla53ikqlhqk FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: recruit_process_items fk313anw2v676rx72cmovtwvnfm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_process_items
    ADD CONSTRAINT fk313anw2v676rx72cmovtwvnfm FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: reports fk3eh6wl6wak38rgcyc3c2acm05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk3eh6wl6wak38rgcyc3c2acm05 FOREIGN KEY (handled_by) REFERENCES public.users(user_id);


--
-- Name: comment_likes fk3wa5u7bs1p1o9hmavtgdgk1go; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk3wa5u7bs1p1o9hmavtgdgk1go FOREIGN KEY (comment_id) REFERENCES public.comments(comment_id);


--
-- Name: comments fk59vpjvskq9e0dfbarx7w57n4j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk59vpjvskq9e0dfbarx7w57n4j FOREIGN KEY (deleted_by) REFERENCES public.users(user_id);


--
-- Name: posts fk5lidm6cqbc7u4xhqpxm898qme; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk5lidm6cqbc7u4xhqpxm898qme FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: member_service_stack fk5nmsx6sb4iwh4eoj6x0ici8df; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_service_stack
    ADD CONSTRAINT fk5nmsx6sb4iwh4eoj6x0ici8df FOREIGN KEY (service_id) REFERENCES public.member_services(service_id);


--
-- Name: comment_likes fk6h3lbneryl5pyb9ykaju7werx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk6h3lbneryl5pyb9ykaju7werx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: post_histories fk6n0bd1aj3n3tb74xf9ayiwjj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_histories
    ADD CONSTRAINT fk6n0bd1aj3n3tb74xf9ayiwjj FOREIGN KEY (post_id) REFERENCES public.posts(post_id);


--
-- Name: posts fk78qo1gxd85rcxqojt2cpcmuj6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fk78qo1gxd85rcxqojt2cpcmuj6 FOREIGN KEY (board_id) REFERENCES public.boards(board_id);


--
-- Name: comments fk7h839m3lkvhbyv3bcdv7sm4fj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk7h839m3lkvhbyv3bcdv7sm4fj FOREIGN KEY (parent_comment_id) REFERENCES public.comments(comment_id);


--
-- Name: user_sanctions fk7k68smbvt3mncbgxg6cc1qesq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sanctions
    ADD CONSTRAINT fk7k68smbvt3mncbgxg6cc1qesq FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- Name: boards fk7kt8hby5livgmjj15f79e9t6v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.boards
    ADD CONSTRAINT fk7kt8hby5livgmjj15f79e9t6v FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: instance_application_files fk9k170upop9efej9evqiwirt06; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.instance_application_files
    ADD CONSTRAINT fk9k170upop9efej9evqiwirt06 FOREIGN KEY (application_id) REFERENCES public.instance_applications(application_id);


--
-- Name: post_likes fka5wxsgl4doibhbed9gm7ikie2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fka5wxsgl4doibhbed9gm7ikie2 FOREIGN KEY (post_id) REFERENCES public.posts(post_id);


--
-- Name: resources fkbupcluevcj2nrn5eo6nuttoin; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT fkbupcluevcj2nrn5eo6nuttoin FOREIGN KEY (post_id) REFERENCES public.posts(post_id);


--
-- Name: admin_action_logs fkcgp592vydgfp5fruikg0mmnm3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_action_logs
    ADD CONSTRAINT fkcgp592vydgfp5fruikg0mmnm3 FOREIGN KEY (admin_id) REFERENCES public.users(user_id);


--
-- Name: resources fkcoba1blh4w96p6n34i4xfoiyp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT fkcoba1blh4w96p6n34i4xfoiyp FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: reports fkd3qiw2om5d2oh5xb7fbdcq225; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkd3qiw2om5d2oh5xb7fbdcq225 FOREIGN KEY (reporter_id) REFERENCES public.users(user_id);


--
-- Name: recruit_applications fkd4xvpu5599w50o58qylr6annu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_applications
    ADD CONSTRAINT fkd4xvpu5599w50o58qylr6annu FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: recruit_tech_stack fkdadb7ld21nktq6j8ye6vgepak; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_tech_stack
    ADD CONSTRAINT fkdadb7ld21nktq6j8ye6vgepak FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: attachments fkdhqpmvosdhj9m39hakmxqk67a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fkdhqpmvosdhj9m39hakmxqk67a FOREIGN KEY (deleted_by) REFERENCES public.users(user_id);


--
-- Name: public_user_activity_logs fkdjbiobpvqb4xci9qw7bwopopv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_activity_logs
    ADD CONSTRAINT fkdjbiobpvqb4xci9qw7bwopopv FOREIGN KEY (profile_id) REFERENCES public.public_user_profiles(profile_id);


--
-- Name: recruit_tags fkfexpvshu1wa23uqqi4asywygr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_tags
    ADD CONSTRAINT fkfexpvshu1wa23uqqi4asywygr FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: comments fkh4c7lvsc298whoyd4w9ta25cr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES public.posts(post_id);


--
-- Name: user_sanctions fkidu102sqbykytiw1fsvvfd0pp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_sanctions
    ADD CONSTRAINT fkidu102sqbykytiw1fsvvfd0pp FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: recruit_applications fkieeqtcp1v5ebi0xn0di0vxr74; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_applications
    ADD CONSTRAINT fkieeqtcp1v5ebi0xn0di0vxr74 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: public_user_awards fkk6iq0ugw8cm2dcnxtb1gh3wd4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_awards
    ADD CONSTRAINT fkk6iq0ugw8cm2dcnxtb1gh3wd4 FOREIGN KEY (profile_id) REFERENCES public.public_user_profiles(profile_id);


--
-- Name: post_likes fkkgau5n0nlewg6o9lr4yibqgxj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fkkgau5n0nlewg6o9lr4yibqgxj FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: comment_histories fkl2jw7a0a2j4huq0q4ubttn7iy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_histories
    ADD CONSTRAINT fkl2jw7a0a2j4huq0q4ubttn7iy FOREIGN KEY (actor_id) REFERENCES public.users(user_id);


--
-- Name: member_service_features fklpa91af6qecykriw0uf5u8w9a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_service_features
    ADD CONSTRAINT fklpa91af6qecykriw0uf5u8w9a FOREIGN KEY (service_id) REFERENCES public.member_services(service_id);


--
-- Name: post_histories fklt7w4qfno6gstwu7xcsq7brxy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_histories
    ADD CONSTRAINT fklt7w4qfno6gstwu7xcsq7brxy FOREIGN KEY (actor_id) REFERENCES public.users(user_id);


--
-- Name: recruit_comments fkml6j8k8syxt3w7umf4u6cawdj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_comments
    ADD CONSTRAINT fkml6j8k8syxt3w7umf4u6cawdj FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: member_service_tags fkobedqtj9fxc3l8ank401lqxpg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_service_tags
    ADD CONSTRAINT fkobedqtj9fxc3l8ank401lqxpg FOREIGN KEY (service_id) REFERENCES public.member_services(service_id);


--
-- Name: recruit_roles fkpudsigl2mj033n2k1xurtocs1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruit_roles
    ADD CONSTRAINT fkpudsigl2mj033n2k1xurtocs1 FOREIGN KEY (recruit_id) REFERENCES public.recruit_posts(recruit_id);


--
-- Name: posts fkr2pufx4n0tm911hoqj7kdqgh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT fkr2pufx4n0tm911hoqj7kdqgh FOREIGN KEY (deleted_by) REFERENCES public.users(user_id);


--
-- Name: attachments fkr60r9lnkb1bv66bqanw3vb4ne; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fkr60r9lnkb1bv66bqanw3vb4ne FOREIGN KEY (uploader_id) REFERENCES public.users(user_id);


--
-- Name: comment_histories fkr7f02qvfoug3h5497o99cr4ia; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_histories
    ADD CONSTRAINT fkr7f02qvfoug3h5497o99cr4ia FOREIGN KEY (comment_id) REFERENCES public.comments(comment_id);


--
-- Name: public_user_profile_repositories fktkkfdl5br0vnhc4agce5552vc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.public_user_profile_repositories
    ADD CONSTRAINT fktkkfdl5br0vnhc4agce5552vc FOREIGN KEY (profile_id) REFERENCES public.public_user_profiles(profile_id);


--
-- PostgreSQL database dump complete
--

