ALTER TABLE public.boards DROP CONSTRAINT IF EXISTS boards_type_check;
ALTER TABLE public.boards ADD CONSTRAINT boards_type_check
    CHECK (((type)::text = ANY ((ARRAY['NORMAL'::character varying, 'RECRUIT'::character varying, 'ANONYMOUS'::character varying])::text[])));

CREATE TABLE IF NOT EXISTS public.anonymous_profiles (
    anonymous_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint NOT NULL REFERENCES public.boards(board_id),
    user_id bigint NOT NULL REFERENCES public.users(user_id),
    display_name character varying(50) NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_anonymous_profiles_board_user UNIQUE (board_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_anonymous_profiles_user
    ON public.anonymous_profiles (user_id);
