CREATE TABLE info_article_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    info_article_id BIGINT NOT NULL REFERENCES info_articles(info_article_id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_info_bookmarks_user_article UNIQUE (user_id, info_article_id)
);

CREATE INDEX idx_info_bookmarks_article ON info_article_bookmarks (info_article_id);
