CREATE TABLE IF NOT EXISTS archive_items (
    archive_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(30) NOT NULL,
    owner_user_id bigint REFERENCES users(user_id),
    owner_name varchar(80) NOT NULL,
    title varchar(150) NOT NULL,
    summary varchar(500) NOT NULL,
    content text NOT NULL,
    source_url varchar(500) NOT NULL DEFAULT '',
    repository_url varchar(500) NOT NULL DEFAULT '',
    tags varchar(500) NOT NULL DEFAULT '',
    created_at timestamp,
    updated_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_archive_items_category
    ON archive_items (category);

CREATE INDEX IF NOT EXISTS idx_archive_items_owner
    ON archive_items (owner_user_id);

CREATE INDEX IF NOT EXISTS idx_archive_items_created
    ON archive_items (created_at);
