ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_bio VARCHAR(1000);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_activity_note TEXT;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_award_note TEXT;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS profile_shared_repositories VARCHAR(1000);
