CREATE TABLE study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruit_id VARCHAR(80) NOT NULL UNIQUE REFERENCES recruit_posts(recruit_id),
    name VARCHAR(80) NOT NULL
);
CREATE TABLE study_records (
    id VARCHAR(36) PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES study_groups(id),
    title VARCHAR(120) NOT NULL,
    activity_date DATE NOT NULL,
    content TEXT NOT NULL,
    author_id BIGINT NOT NULL REFERENCES users(user_id),
    updated_by BIGINT NOT NULL REFERENCES users(user_id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX idx_study_records_date ON study_records(activity_date);
CREATE INDEX idx_study_records_group_date ON study_records(group_id, activity_date);
CREATE TABLE study_attendance (
    record_id VARCHAR(36) NOT NULL REFERENCES study_records(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    status VARCHAR(12) NOT NULL CHECK (status IN ('present', 'late', 'absent', 'unknown')),
    PRIMARY KEY(record_id, user_id)
);
CREATE INDEX idx_study_attendance_user ON study_attendance(user_id);
