CREATE TABLE IF NOT EXISTS public.info_article_likes (
    info_article_like_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(user_id),
    info_article_id bigint NOT NULL REFERENCES public.info_articles(info_article_id) ON DELETE CASCADE,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_info_article_like_user_article UNIQUE (user_id, info_article_id)
);

CREATE INDEX IF NOT EXISTS idx_info_article_likes_article
    ON public.info_article_likes (info_article_id);

CREATE INDEX IF NOT EXISTS idx_info_article_likes_user
    ON public.info_article_likes (user_id);
