CREATE TABLE IF NOT EXISTS public.notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(user_id),
    type varchar(40) NOT NULL,
    title varchar(120) NOT NULL,
    message varchar(500) NOT NULL,
    link_url varchar(500),
    read_at timestamp,
    created_at timestamp,
    updated_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created
    ON public.notifications (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read
    ON public.notifications (user_id, read_at);
