CREATE TABLE site_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    eyebrow VARCHAR(80) NOT NULL DEFAULT '',
    description VARCHAR(2000) NOT NULL DEFAULT '',
    image_url VARCHAR(2000) NOT NULL DEFAULT '',
    target_path VARCHAR(500) NOT NULL,
    action_label VARCHAR(40) NOT NULL,
    tone VARCHAR(10) NOT NULL CHECK (tone IN ('green', 'blue', 'coral')),
    sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_site_banners_display ON site_banners (enabled, sort_order, id);

INSERT INTO site_banners (title, eyebrow, description, image_url, target_path, action_label, tone, sort_order, enabled)
VALUES
    ('COALA Developer Club', 'TOGETHER WE BUILD', '함께 만들고 운영하는 개발 동아리', '', '/about', '동아리 소개', 'green', 0, TRUE),
    ('배우고, 나누고, 함께.', 'COMMUNITY', '새로운 이야기와 함께할 사람들을 만나보세요.', '', '/community/board', '커뮤니티', 'blue', 1, TRUE),
    ('아이디어에서 서비스로.', 'MADE BY COALA', '코알라가 만들고 운영하는 서비스를 만나보세요.', '', '/services', '서비스 보기', 'coral', 2, TRUE);
