CREATE TABLE IF NOT EXISTS recruit_bookmarks (
    bookmark_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recruit_id varchar(80) NOT NULL REFERENCES recruit_posts(recruit_id),
    user_id bigint NOT NULL REFERENCES users(user_id),
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_recruit_bookmarks_user_recruit UNIQUE (user_id, recruit_id)
);

CREATE INDEX IF NOT EXISTS idx_recruit_bookmarks_user
    ON recruit_bookmarks (user_id);

CREATE INDEX IF NOT EXISTS idx_recruit_bookmarks_recruit
    ON recruit_bookmarks (recruit_id);
